"""application staging: screenshot and notes columns

Revision ID: 4a07434c1b6b
Revises: a2d48cc12da2
Create Date: 2026-09-02 21:55:18.638397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a07434c1b6b'
down_revision: Union[str, None] = 'a2d48cc12da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('staged_screenshot_path', sa.String(length=1000), nullable=True))
    op.add_column('applications', sa.Column('staging_notes', sa.JSON(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'staging_notes')
    op.drop_column('applications', 'staged_screenshot_path')
    # ### end Alembic commands ###
